language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: ekiNvug+ALgYHj9+zzG/6S1TJGnZPZ7mPmVQp9qldWNiMJSH2tW8V84EBn04RWMmWI6kEzeN3DOcroDzoTuOKwiEdlU/LjK3cCW4nZatlqNPpObW+yzs6+eb//GFTPHcNjK6yQlyznLP7OKAvujuJK0yx8odIZmwU5SsIg6uDDyr1sp+PIst5pVfHIej32/fq6PUhEx2jPOkwYkiR6dwTzef3P20JbvVL2ySbomTSrZrAs/N/NJXq5ja4ZvKlc6vVi/sT2R0gWOpWMBSw695He3NdMnYjTQzaybZs+MOCiqSpmeJUrUY+QIz67xq+kBTY0xLAP2iKvbotLWiONLSALadc4HlQxinDy2PeMXtT6TXfNsFdaaNWaT/mED77jSimeW5pRF0RzT/uKX9mXb43sxZo6sWBUpqbudo5MCls65OWfF/kQhfT4p+YZoqoA7gidgqIKHvXjo5n+g6nk85QtLFbaLdVqGIprdjFVfr/mEbt+l4i54TnfOWqovy4zciUtnHJfCS9c7U0PfNnb/qBQz1Qh2lc2KsMBTGev9+WHugFoXumwyx970Z7JYXzP24D3RRqWtWZTVQJBykAfguIAPzcaqo5yMfsP3oBGAOSQnRB+vRskzJOsPZONv8NUWa4Pux6QhqcE1r1b7i/BEsLiH3Z/QKh8E9UUvDWL+++8g=
  app: animalstrade
  on:
    repo: lazyfox93/homework_ror
    branch: dev
